@startuml
database FileIndex {
}
database Database {
}
database Events {
}
card Export [
  Export Meta
]
folder Files {
}

FileIndex -down-> Export
Database -down-> Export
Events -down-> Export
Export -down-> Files
@enduml